# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

StoEval <- function(X0, q, crit = 0L) {
    .Call(`_UniDOE_StoEval`, X0, q, crit)
}

StoUDC <- function(n, s, q, init, initX, crit, maxiter, hits_ratio) {
    .Call(`_UniDOE_StoUDC`, n, s, q, init, initX, crit, maxiter, hits_ratio)
}

StoAUDC <- function(XP, n, s, q, init, initX, crit, maxiter, hits_ratio) {
    .Call(`_UniDOE_StoAUDC`, XP, n, s, q, init, initX, crit, maxiter, hits_ratio)
}

StoLP <- function(X0, q, crit, maxiter, hits_ratio) {
    .Call(`_UniDOE_StoLP`, X0, q, crit, maxiter, hits_ratio)
}

